name: Participations

on: [push]

jobs:
  presence:
    name: presence de fichiers pour la participation
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
    
      - shell: bash
        run: |
          ##
          ## Evaluating chapter 0.PlanDeCours
          ## 
          echo "Evaluating chapter 0.PlanDeCours Participation"
          cd 0.PlanDeCours
          bash .scripts/run.sh
          cd ..
          ##
          ## Evaluating manual githug commit/push
          ## 
          echo "Evaluating git commands Participation"
          bash .scripts/run.sh
          ##
<<<<<<< HEAD
          ## Evaluating chapter 1.SSH
=======
          ## Evaluating chapter 1.SSH Participation
>>>>>>> bfd96a15e0e759c85b338713c638dfac8a07f550
          ## 
          echo "Evaluating chapter 1.SSH Participation"
          cd 1.SSH
          bash .scripts/run.sh
          cd ..
<<<<<<< HEAD
=======
          ##
          ## Evaluating chapter 2.Utilisateurs Participation
          ## 
          echo "Evaluating chapter 2.Utilisateurs Participation"
          cd 2.Utilisateurs
          bash .scripts/run.sh
          cd ..
>>>>>>> bfd96a15e0e759c85b338713c638dfac8a07f550

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "VÃ©rification de la participation" -a
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
